-- Azul Gestao - protecao contra tentativas repetidas de recuperacao.
-- Executar no Supabase de teste e no Supabase de producao.

create table if not exists public.password_reset_attempts (
  id bigint generated by default as identity primary key,
  fingerprint text not null,
  success boolean not null default false,
  created_at timestamp with time zone not null default now()
);

create index if not exists password_reset_attempts_fingerprint_created_idx
  on public.password_reset_attempts (fingerprint, created_at desc);

alter table public.password_reset_attempts enable row level security;

revoke all on table public.password_reset_attempts from public, anon, authenticated;

